//2 namespaces from MongoDBdriver
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace StudentManagement.Models
{
    //We want the Id property in student class to be mapped to the autogenerated ID in MongoDB.
    //We use Bson attribute for this 
    public class Student
    {
        public string Id { get; set; } = String.Empty;//What is string.empty?
        public string Name { get; set; } = String.Empty;
        public bool IsGraduated { get; set; }
        public int Age { get; set; }
        public string[]? Courses { get; set; }
        //? means that it can be null (nullable). without ? - warning thrown that courses cannot be null
        public string Gender { get; set; } = String.Empty;
    }
}
